import { Roboto, Sofia_Sans } from "next/font/google";
import { SidebarProvider } from "@/context/SidebarContext";
import { MenuProvider } from "@/context/MenuContext";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic", "latin"],
  display: "swap",
});

const sofia = Sofia_Sans({
  variable: "--font-sofia",
  subsets: ["cyrillic", "latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${roboto.variable} ${sofia.variable}`}>
      <head></head>
      <MenuProvider>
        <SidebarProvider>
          {/* <UTMCookieSaver /> */}
          {children}
          {/* <Modal /> */}
        </SidebarProvider>
      </MenuProvider>
    </html>
  );
}
